[package]
name = "rust-lambda-template"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
lambda_runtime = "0.13.0"
log = "0.4.22"
serde_json = "1.0.132"
tokio = "1.41.0"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
